# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setMaximumSize(QtCore.QSize(1501, 920))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.back_ground = QtWidgets.QWidget(self.centralwidget)
        self.back_ground.setGeometry(QtCore.QRect(10, 0, 1200, 900))
        self.back_ground.setStyleSheet("\n"
"background-color: rgb(245,245,245);")
        self.back_ground.setObjectName("back_ground")
        self.stripes = QtWidgets.QLabel(self.back_ground)
        self.stripes.setGeometry(QtCore.QRect(20, 20, 481, 821))
        self.stripes.setStyleSheet("background-image: url(:/newPrefix/leaf.png);")
        self.stripes.setText("")
        self.stripes.setPixmap(QtGui.QPixmap(":/newPrefix/leaf.png"))
        self.stripes.setScaledContents(True)
        self.stripes.setWordWrap(False)
        self.stripes.setObjectName("stripes")
        self.form_background = QtWidgets.QLabel(self.back_ground)
        self.form_background.setGeometry(QtCore.QRect(-40, 0, 1221, 841))
        self.form_background.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.form_background.setText("")
        self.form_background.setObjectName("form_background")
        self.Login = QtWidgets.QPushButton(self.back_ground)
        self.Login.setGeometry(QtCore.QRect(640, 150, 141, 51))
        font = QtGui.QFont()
        font.setFamily("Istok Web")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.Login.setFont(font)
        self.Login.setStyleSheet(" font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 30px;\n"
"            line-height: 38px;\n"
"            color: #5F7C8D;\n"
"background-color: transparent;")
        self.Login.setObjectName("Login")
        self.signup = QtWidgets.QPushButton(self.back_ground)
        self.signup.setGeometry(QtCore.QRect(900, 160, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Istok Web")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(87)
        self.signup.setFont(font)
        self.signup.setStyleSheet(" font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-weight: 700;\n"
"            font-size: 30px;\n"
"            line-height: 38px;\n"
"            color: #5F7C8D;\n"
"background-color: transparent;")
        self.signup.setObjectName("signup")
        self.line = QtWidgets.QFrame(self.back_ground)
        self.line.setGeometry(QtCore.QRect(910, 200, 138, 3))
        self.line.setStyleSheet("position: absolute;\n"
"            width: 90px;\n"
"            height: 0px;\n"
"            left: -23px;\n"
"            top: 52px;\n"
"            border: 3px solid #5F7C8D;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.back_ground)
        self.line_2.setGeometry(QtCore.QRect(620, 350, 441, 2))
        self.line_2.setStyleSheet("  position: absolute;\n"
"            width: 432.17px;\n"
"            height: 1px;\n"
"            left: 691px;\n"
"            top: 414px;\n"
"            background: #5F7C8D;")
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.back_ground)
        self.line_3.setGeometry(QtCore.QRect(620, 620, 441, 2))
        self.line_3.setStyleSheet("  position: absolute;\n"
"            width: 432.17px;\n"
"            height: 1px;\n"
"            left: 691px;\n"
"            top: 414px;\n"
"            background: #5F7C8D;")
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Login_button = QtWidgets.QPushButton(self.back_ground)
        self.Login_button.setGeometry(QtCore.QRect(630, 710, 381, 71))
        self.Login_button.setStyleSheet(" position: absolute;\n"
"            width: 432px;\n"
"            height: 73px;\n"
"            left: 691px;\n"
"            top: 581px;\n"
"            background: #4B687A;\n"
" font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-weight: 600;\n"
"            font-size: 28px;\n"
"color : white")
        self.Login_button.setObjectName("Login_button")
        self.username = QtWidgets.QLineEdit(self.back_ground)
        self.username.setGeometry(QtCore.QRect(620, 310, 441, 41))
        self.username.setStyleSheet("background: transparent;\n"
"            font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-size: 22px;\n"
"            color: rgba(95, 124, 141, 0.55);\n"
" letter-spacing: 0.75px;\n"
"border: none;")
        self.username.setObjectName("username")
        self.username_2 = QtWidgets.QLineEdit(self.back_ground)
        self.username_2.setGeometry(QtCore.QRect(620, 580, 441, 41))
        self.username_2.setStyleSheet("background: transparent;\n"
"            font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-size: 22px;\n"
"            color: rgba(95, 124, 141, 0.55);\n"
" letter-spacing: 0.75px;\n"
" border:none ;")
        self.username_2.setText("")
        self.username_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.username_2.setObjectName("username_2")
        self.Welcome = QtWidgets.QLabel(self.back_ground)
        self.Welcome.setGeometry(QtCore.QRect(720, 10, 291, 81))
        self.Welcome.setStyleSheet("position: absolute;\n"
"width: 410px;\n"
"height: 120px;\n"
"left: 789px;\n"
"top: 52px;\n"
"\n"
"font-family: \'Istok Web\';\n"
"font-style: normal;\n"
"font-weight: 700;\n"
"font-size: 54px;\n"
"line-height: 92px;\n"
"\n"
"color: #7A999C;\n"
"background : transparent;")
        self.Welcome.setObjectName("Welcome")
        self.username_3 = QtWidgets.QLineEdit(self.back_ground)
        self.username_3.setGeometry(QtCore.QRect(620, 400, 441, 41))
        self.username_3.setStyleSheet("background: transparent;\n"
"            font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-size: 22px;\n"
"            color: rgba(95, 124, 141, 0.55);\n"
" letter-spacing: 0.75px;\n"
"border:none;")
        self.username_3.setObjectName("username_3")
        self.line_4 = QtWidgets.QFrame(self.back_ground)
        self.line_4.setGeometry(QtCore.QRect(620, 440, 441, 2))
        self.line_4.setStyleSheet("  position: absolute;\n"
"            width: 432.17px;\n"
"            height: 1px;\n"
"            left: 691px;\n"
"            top: 414px;\n"
"            background: #5F7C8D;")
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.username_4 = QtWidgets.QLineEdit(self.back_ground)
        self.username_4.setGeometry(QtCore.QRect(620, 500, 441, 41))
        self.username_4.setStyleSheet("background: transparent;\n"
"            font-family: \'Istok Web\';\n"
"            font-style: normal;\n"
"            font-size: 22px;\n"
"            color: rgba(95, 124, 141, 0.55);\n"
" letter-spacing: 0.75px;\n"
"border:none;")
        self.username_4.setObjectName("username_4")
        self.line_5 = QtWidgets.QFrame(self.back_ground)
        self.line_5.setGeometry(QtCore.QRect(620, 540, 441, 2))
        self.line_5.setStyleSheet("  position: absolute;\n"
"            width: 432.17px;\n"
"            height: 1px;\n"
"            left: 691px;\n"
"            top: 414px;\n"
"            background: #5F7C8D;")
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.form_background.raise_()
        self.Login.raise_()
        self.signup.raise_()
        self.line.raise_()
        self.line_2.raise_()
        self.line_3.raise_()
        self.Login_button.raise_()
        self.username.raise_()
        self.username_2.raise_()
        self.Welcome.raise_()
        self.stripes.raise_()
        self.username_3.raise_()
        self.line_4.raise_()
        self.username_4.raise_()
        self.line_5.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Login.setText(_translate("MainWindow", "Login"))
        self.signup.setText(_translate("MainWindow", "SignUp"))
        self.Login_button.setText(_translate("MainWindow", "Sign Up"))
        self.username.setPlaceholderText(_translate("MainWindow", "Username"))
        self.username_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.Welcome.setText(_translate("MainWindow", "Welcome"))
        self.username_3.setPlaceholderText(_translate("MainWindow", "Email"))
        self.username_4.setPlaceholderText(_translate("MainWindow", "Contact Number"))
import stripes_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
